---
# _config.yml

# 多语言支持配置
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 语言设置
active_lang: "en"  # 默认语言
languages: ["en", "zh"]

# 排除不需要处理的文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - assets/css/style.css.map

# 网站基本信息
url: "https://globularcluster.ca"
baseurl: ""  # 如果网站在根目录，则为空

# 网站标题与描述
title: "Globular Cluster Technology Software Limited"
email: "support@globularcluster.ca"
description: "提供服务：AWS云平台成本节省，公司IT业务优化，公司网站设计和建设"
author:
  name: "Kasen Li"
  email: "support@globularcluster.ca"

remote_theme: raviriley/agency-jekyll-theme

# 页面导航设置（主语言）
navigation:
  - text: About
    url: "#about"
  - text: Services
    url: "#services"
  # - text: Portfolio
  #   url: "#portfolio"
  - text: Team
    url: "#team"
  - text: Contact
    url: "#contact"

# 联系方式
contact:
  name: "Globular Cluster Technology Software Limited"
  address: "Vancouver, Canada"
  email: "support@globularcluster.ca"
  # phone: "+1 (123) 456-7890"

# social:
#   github: yourusername
#   linkedin: yourlinkedin
#   twitter: yourtwitter

github:
  is_project_page: false

markdown: kramdown
kramdown:
  input: GFM