# _config.yml

plugins:
  - jekyll-feed
  - jekyll-seo-tag


# # 排除不需要处理的文件
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor
#   - assets/css/style.css.map

# 网站基本信息
url: "https://globularcluster.ca"
baseurl: ""

# 网站标题与描述
title: "Globular Cluster Technology Software Limited"
email: "support@globularcluster.ca"
description: "提供服务：AWS云平台成本节省，公司IT业务优化，公司网站设计和建设"
author: "Kasen Li"

logo:
  path: logo.png

# theme: jekyll-agency
remote_theme: raviriley/agency-jekyll-theme  ## 与参考配置不同，但可用
locale: "en-US"

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:


markdown: kramdown
kramdown:
  input: GFM
